version: "3"

services:

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.14
    # macOS silicon
    # image: arm64v8/elasticsearch:7.17.14
    restart: always
    container_name: es
    environment:
      - node.name=es
      - cluster.name=es-cluster
      # run single
      - discovery.type=single-node
      # 不信任的ssl憑證
      - xpack.security.enabled=false
      # 用于设置 Elasticsearch (ES) 运行时 Java 虚拟机 (JVM) 参数的环境变量。
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - web_service


volumes:
  es_data:

networks:
  web_service: