version: '3'
services:

  kibana:
      image: docker.elastic.co/kibana/kibana:8.8.0
      container_name: kibana
      restart: always
      environment:
        - ELASTICSEARCH_HOSTS=http://es01:9200
      ports:
        - 5601:5601
      networks:
        - web_service

networks:
  web_service:
    external: true