version: '3'

services:
  kafka:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8081:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    volumes:
      - ./config.yaml:/etc/kafkaui/dynamic_config.yaml
    networks:
      - web_service
networks:
  web_service:
    external: true