version: '3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: PHPmyadmin
    environment:
        - PMA_ARBITRARY=1
        # - PMA_HOSTS=melon-db # 可供使用者選擇伺服器
    restart: always
    ports:
        - 5555:80
    networks:
      - web_service
networks:
  web_service:
    external: true