version: '3'

services:
  portainer:
    image: portainer/portainer:linux-amd64-2.0.1
    container_name: portainer
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # 掛載設定檔
      - ${VOLUME_PATH}/Portainer:/data
    networks:
      - portainer_service
networks:
  portainer_service:
    external: true