version: '3.8'

services:
  mongo1:
    image: mongo
    container_name: mongo1
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    networks:
      - mongo-network

  mongo2:
    image: mongo
    container_name: mongo2
    ports:
      - "27018:27017"
    depends_on:
      - mongo1
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    networks:
      - mongo-network

  mongo3:
    image: mongo
    container_name: mongo3
    ports:
      - "27019:27017"
    depends_on:
      - mongo1
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    networks:
      - mongo-network

  init-replica-set:
    image: mongo
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - mongo-network
    command: >
      bash -c "sleep 20 &&
      mongosh --host mongo1:27017 --eval '
      rs.initiate({
        _id: \"rs0\",
        members: [
          { _id: 0, host: \"mongo1:27017\" },
          { _id: 1, host: \"mongo2:27017\" },
          { _id: 2, host: \"mongo3:27017\" }
        ]
      })'"

networks:
  mongo-network:
    driver: bridge
